[supervisord]
nodaemon=true

[program:postgres]
command=/usr/lib/postgresql/15/bin/postgres -D /var/lib/postgresql/data
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:springboot]
command=/bin/bash -c "until pg_isready -U postgres -d promptdb; do echo waiting for postgres...; sleep 2; done; java -jar /app/app.jar"
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
