spring:
  application:
    name: prompt-manager
#  profiles:
#    active: dev

  sql:
    init:
      mode: always # Execute scripts on initialization
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql

  jackson:
    serialization:
      fail-on-empty-beans: true # fail if receive properties no defined in dto

info:
  app:
    name: Prompt Manager
    description: Backend REST API for prompt manager
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.http.converter.json: DEBUG
    org.springframework.boot.actuate.endpoint.web: DEBUG
